apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: podinfo
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - hpa.yaml

labels:
  - pairs:
      app.kubernetes.io/name: podinfo
      waaghals.dev/team: development-team-1
