name: Overlays
on: pull_request
jobs:
  promotable-sync:
    runs-on: ubuntu-latest
    name: Promotable ${{ matrix.type }}
    strategy:
      matrix:
        include:
          - type: source
            query: .on.workflow_dispatch.inputs.source.options
            message: Promote workflow **source** environments are not in sync with environments from overlay directory
            file: source.yaml
          - type: target
            query: .on.workflow_dispatch.inputs.target.options
            message: Promote workflow **target** environments are not in sync with environments from overlay directory
            file: target.yaml
    steps:
      - name: Find comment
        uses: sandeshjangam/comment-actions@v1
        id: find_comment
        with:
          type: find
          search_term: ${{ matrix.message }}
          number: ${{ github.event.pull_request.number }}
      - name: Delete comment
        uses: sandeshjangam/comment-actions@v1
        id: delete_comment
        if: ${{ steps.find_comment.outputs.comment_id != '' }}
        with:
          type: delete
          comment_id: ${{ steps.find_comment.outputs.comment_id }}
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Determine actual overlays
        run: |
          cd overlays
          find * -type d -exec echo "- {}" \; > ../overlays.yaml
          cd ..
      - name: Determine promotable overlays
        run: yq '${{ matrix.query }} | unique | sort' .github/workflows/promote.yaml > ${{ matrix.file }}
      - name: Diff
        run: git diff --no-index --ignore-space-at-eol --no-renames overlays.yaml ${{ matrix.file }}
      - name: Leave comment
        if: failure()
        uses: sandeshjangam/comment-actions@v1
        id: create_delete_comment
        with:
          type: create
          body: ${{ matrix.message }}
          number: ${{ github.event.pull_request.number }}
